This is in separate notebook because open3d lib didn't want to work with other libraries

In [1]:
import open3d as o3d
import numpy as np
from pathlib import Path
from pyntcloud import PyntCloud
import point_cloud_utils as pcu

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.

In [3]:
model_path = "../results/sks/hedgehog/model.ply"

In [4]:
model_pc = PyntCloud.from_file(model_path)

In [5]:
# sensor_dirs are stored in the normal channel and are encoded as unit
# vectors pointing from the point to the scanner
pts, sensor_dirs = pcu.load_mesh_vf(model_path)

# Optionally delete point whose normal is at an oblique (greather than 85 degree) angle with the sensor direction
drop_angle = np.deg2rad(85.0)

# Size of the neighborhood used for each point
num_nbrs = 32

# n are the fitted normals
# n_idx are used to delete points which were filterd (ignore this if you don't pass in drop_angle)
_, n = pcu.estimate_point_cloud_normals_knn(pts, num_nbrs, view_directions=sensor_dirs)

In [6]:
n

array([[ 0.79892755,  0.5969308 ,  0.07340541],
       [ 0.11131473, -0.2098851 ,  0.9713688 ],
       [ 0.73997694, -0.51859105, -0.42836604],
       ...,
       [ 0.1124795 ,  0.91336733, -0.39129075],
       [ 0.09565829,  0.8112951 , -0.57675797],
       [-0.7005929 , -0.17978047,  0.6905423 ]], dtype=float32)

In [7]:
model_pc.points

,x,y,z,a,q0,q1,q2,q3,s0,s1,...,sh12_z,sh13_x,sh13_y,sh13_z,sh14_x,sh14_y,sh14_z,sh15_x,sh15_y,sh15_z
0,0.481594,0.850698,-0.196319,-1.289389,1.053202,0.777928,0.666606,0.782969,-6.069666,-8.106468,...,0.098698,0.003610,0.001742,-0.002101,0.030575,0.025658,0.040775,-0.126277,-0.111762,-0.132224
1,0.761535,0.716802,-0.214776,-1.244070,0.821183,0.930334,-0.177495,0.306206,-3.758905,-5.277179,...,0.022767,-0.047945,-0.037082,-0.095535,0.016211,0.015260,0.024990,0.004395,0.041731,0.004630
2,1.025803,0.269971,-0.120126,-1.104922,0.551044,-0.194463,1.281180,0.393679,-8.181364,-7.613200,...,0.054696,0.032633,0.008218,-0.129743,0.057082,0.067569,0.058694,0.037657,0.036729,0.033269
3,0.475272,0.124009,-0.075317,1.125659,0.566566,0.463456,0.774790,0.489841,-3.742359,-4.793444,...,-0.058047,-0.000428,0.003574,-0.023057,-0.012539,-0.001188,0.000045,-0.044469,-0.053430,-0.051161
4,0.798120,1.040688,-0.023332,1.319954,-0.165604,0.268248,1.040911,0.002683,-6.472095,-7.021164,...,0.025024,-0.016341,-0.024041,-0.023883,0.051209,0.042731,0.051137,0.003423,-0.010310,-0.014037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3685994,-0.212520,0.033916,-0.080550,-0.867877,0.641948,0.461006,0.553307,1.264350,-4.994217,-18.804882,...,-0.022673,-0.033227,-0.100685,-0.082938,-0.024404,0.012880,0.025330,-0.239103,-0.078461,-0.113968
3685995,0.850566,0.431826,0.188341,-2.093014,0.971840,0.620849,0.431704,1.022836,-3.138559,-3.887674,...,0.028839,-0.060037,-0.064375,-0.073136,0.006281,0.005287,-0.003834,0.148534,0.152696,0.154640
3685996,-0.699854,-0.016132,-0.208567,0.350056,0.083633,1.758122,-0.455008,-0.033128,-4.300349,-7.180073,...,0.034278,0.086976,0.076210,0.038362,0.024849,0.032772,-0.003208,-0.104244,-0.098325,-0.103457
3685997,-0.955104,0.792024,-0.202274,-2.293873,1.259638,0.916563,0.488875,0.613027,-4.011404,-8.201948,...,0.019209,0.010984,0.007131,0.017476,0.011271,0.008107,0.033964,0.022125,0.066955,0.087904
3685998,0.314616,-0.638022,0.137728,-2.929590,0.558969,0.332812,-0.025434,0.901521,-2.780837,-20.197399,...,-0.007888,-0.008093,-0.005922,0.042721,0.084852,0.093813,0.049113,-0.141319,-0.174680,-0.149751

In [8]:
model_pc.points[['x', 'y', 'z']] - n

                x         y         z
0       -0.317334  0.253767 -0.269724
1        0.650220  0.926688 -1.186145
2        0.285826  0.788562  0.308240
3       -0.382557 -0.281475 -0.391090
4        1.485406  0.535690 -0.545457
...           ...       ...       ...
3685994  0.213768 -0.722578  0.415430
3685995  1.334774 -0.443094  0.180770
3685996 -0.812334 -0.929500  0.182724
3685997 -1.050762 -0.019271  0.374484
3685998  1.015209 -0.458242 -0.552814

[3685999 rows x 3 columns]

In [10]:
np.array([1, 2, 3]) * np.array([3, 3, 3])

array([3, 6, 9])

In [41]:
np.min(n, axis=0), np.max(n, axis=0)

(array([-0.8069381 , -0.8006618 , -0.79774684], dtype=float32),
 array([0.99999994, 1.        , 0.9999997 ], dtype=float32))

In [42]:
def compute_colors_from_harmonics(points, normals):
    SH_C0 = 0.28209479177387814
    SH_C1 = 0.4886025119029199
    p = (points[['x', 'y', 'z']].values - normals).reshape(-1, 3)
    sh0s = p * SH_C0 * points[['sh0_x', 'sh0_y', 'sh0_z']].values
    
    sh1s =  SH_C1 * (p[:, [1]] * points[['sh1_x', 'sh1_y', 'sh1_z']].values + p[:, [2]] * points[['sh1_x', 'sh1_y', 'sh1_z']].values - p[:, [0]] * points[['sh1_x', 'sh1_y', 'sh1_z']].values)
    
    res = sh0s - sh1s + 0.5
    
    return np.where(res > 0, res, 0)

In [43]:
np.max(compute_colors_from_harmonics(model_pc.points[:100], n[:100]))

1.4128329

In [28]:
r_1

array([[-5.96467406e-03, -5.29630575e-03, -7.46935513e-03],
       [ 1.86993129e-04,  2.22313858e-04,  2.53133569e-03],
       [-1.02910176e-02, -1.20486952e-02, -1.06166005e-02],
       [-2.03548581e-03, -2.35354085e-03, -2.48595676e-03],
       [-2.82961316e-02, -2.32792217e-02, -2.08549406e-02],
       [ 5.76229068e-04,  7.71325780e-04, -1.41117898e-05],
       [ 8.88771098e-03, -1.70557965e-02, -9.00180452e-03],
       [-8.34993366e-03, -8.65427218e-03, -9.46132839e-03],
       [-8.66267597e-04, -1.42622693e-03, -1.93585723e-03],
       [ 8.87208269e-04, -5.42046176e-03, -6.59316825e-03],
       [-8.48000986e-04,  5.31585421e-03,  5.80310216e-03],
       [-6.48344774e-03, -1.49387158e-02, -3.05383820e-02],
       [-2.01966046e-04, -1.37198585e-04, -3.23062588e-04],
       [ 4.49591596e-03,  5.13772946e-03,  5.11580426e-03],
       [ 1.59075707e-02,  8.79015960e-03,  7.14447815e-03],
       [ 2.97417734e-02,  2.44924277e-02,  9.16816667e-03],
       [-1.82482094e-04,  4.28391068e-05,  9.94457863e-04],
       [-1.58502930e-03, -1.76903978e-03, -4.51864582e-03],
       [-1.07458886e-03, -1.35768240e-03, -8.54482350e-04],
       [-1.42868599e-02, -1.55179175e-02, -9.34118871e-03],
       [-1.44239636e-02, -6.80156192e-03,  1.13035291e-02],
       [-4.52733738e-03, -4.79655107e-03, -5.47337718e-03],
       [ 4.04311642e-02,  3.46793011e-02,  2.10321322e-02],
       [ 3.57402884e-03,  4.39344533e-03,  2.44330522e-03],
       [-1.85008850e-02, -1.75053328e-02, -2.02721022e-02],
       [ 1.33702178e-02,  9.32855252e-03,  4.22939425e-03],
       [ 1.98190054e-03,  3.93586047e-03,  2.66379747e-03],
       [-8.53826571e-03, -5.84851205e-03, -1.21618938e-02],
       [ 4.27629612e-02,  3.81655991e-02,  4.41776738e-02],
       [-2.16824897e-02, -2.12763213e-02,  7.10757030e-03],
       [ 1.11038575e-03,  1.74886384e-03,  1.99950463e-03],
       [-6.34834229e-04, -7.04121077e-04,  1.27563311e-03],
       [-2.91350554e-03, -3.27475765e-03, -2.71540531e-03],
       [-7.84799224e-04, -3.51292011e-03, -1.03801396e-03],
       [-4.58944123e-03, -8.67877214e-04, -6.24549948e-03],
       [ 1.05219269e-02,  1.57799590e-02,  1.76369641e-02],
       [ 1.22100916e-02,  1.34698022e-02,  1.35571146e-02],
       [-4.48221853e-03, -1.01394411e-02, -1.10588511e-02],
       [ 2.32057273e-03, -1.58538064e-03, -7.64584495e-03],
       [ 2.21507866e-02,  2.07853764e-02,  2.82913093e-02],
       [ 2.47359741e-03,  8.57807579e-04, -1.23746833e-02],
       [ 9.67837404e-04,  2.95896060e-03,  4.98818327e-03],
       [-3.29602999e-03, -2.52157496e-03,  1.58421893e-03],
       [-1.11041563e-02, -7.63510307e-03, -5.26656285e-02],
       [ 2.67337877e-02,  2.77310461e-02,  3.38683613e-02],
       [-6.85334438e-03, -6.62278477e-03, -8.49364419e-03],
       [-1.02650153e-03, -6.45304041e-04, -3.48145748e-03],
       [ 3.92212439e-03,  5.74076129e-03,  1.13921817e-02],
       [ 2.81059071e-02,  2.12230422e-02,  2.45642830e-02],
       [-1.01164129e-04,  6.01799751e-04,  0.00000000e+00],
       [-3.60566638e-02, -7.29216710e-02,  2.45371014e-02],
       [-3.96298384e-03, -2.97296653e-03, -4.24822932e-03],
       [-1.51816979e-02, -1.53404130e-02, -1.30327968e-02],
       [ 4.21418920e-02,  4.41695824e-02,  4.31821384e-02],
       [ 2.55563259e-02,  4.00782526e-02,  4.38068584e-02],
       [-1.29896915e-02, -1.32713616e-02, -1.26528759e-02],
       [ 1.08839769e-03,  7.45374477e-04,  5.96120080e-04],
       [ 1.16084507e-02,  1.61312185e-02, -1.40467444e-02],
       [ 4.64708284e-02,  4.77898568e-02,  4.98785488e-02],
       [ 3.98097932e-02,  1.92960594e-02, -6.50219396e-02],
       [-6.24759635e-03, -8.47054552e-03, -2.32948065e-02],
       [ 3.54911387e-03,  2.97504244e-03,  2.30647344e-03],
       [ 2.45249784e-03,  3.03703267e-03,  5.12730703e-03],
       [-7.33905239e-03, -6.15195837e-03, -6.40952634e-03],
       [-1.02059739e-02, -1.62694938e-02, -1.98374223e-02],
       [ 2.45152228e-02,  1.79649647e-02, -2.91234162e-03],
       [ 7.44761294e-03,  7.66373752e-03,  1.59127302e-02],
       [-7.96229392e-03, -3.05084907e-03, -1.94135483e-03],
       [ 2.87623629e-02,  1.47050768e-02,  3.99991125e-03],
       [-2.00045463e-02, -2.66733933e-02, -1.54033769e-02],
       [-3.06465998e-02, -3.10403556e-02, -2.00658236e-02],
       [-1.85883173e-03, -2.74475175e-03,  0.00000000e+00],
       [ 2.98210606e-03,  4.79611335e-03,  1.41151564e-03],
       [ 5.33109764e-04,  1.93202670e-03, -4.83128155e-04],
       [ 8.63517821e-03,  9.69037320e-03,  4.49821167e-03],
       [-1.24633676e-04,  2.58298754e-03,  3.91994976e-03],
       [-4.73737158e-03, -5.61846001e-03, -3.76890134e-03],
       [-3.73733323e-03, -1.67717366e-03, -4.18980519e-04],
       [-3.25313173e-02, -3.04133352e-02, -3.94867323e-02],
       [ 7.59247784e-03,  3.33211757e-03,  2.66888435e-03],
       [-3.85730225e-03, -4.13170271e-03, -4.17175377e-03],
       [ 9.14184784e-04,  1.62556744e-03, -1.01984432e-02],
       [ 3.44778108e-03,  4.71664267e-03, -2.73274397e-03],
       [ 9.19633487e-04,  2.05707317e-03,  1.81211694e-03],
       [-1.70720536e-02, -1.51703805e-02, -4.89329977e-04],
       [-3.58496234e-03, -5.44512691e-03, -8.15162435e-03],
       [-8.08593445e-03, -2.32768501e-03,  3.45792482e-03],
       [ 3.57893790e-04, -2.01427797e-03, -2.79529532e-03],
       [ 5.64679271e-03,  8.54177459e-04, -2.50613480e-03],
       [ 1.14887266e-03, -2.18294095e-03,  1.04266470e-02],
       [-4.75662947e-02, -4.37821001e-02, -5.05914874e-02],
       [-9.75680631e-03, -1.03943059e-02, -3.11664958e-02],
       [-7.15974867e-02, -9.04048979e-02, -8.59392509e-02],
       [-2.13750149e-03, -3.90469539e-03, -3.46325547e-03],
       [-3.66280749e-02, -2.72201467e-02, -4.04727198e-02],
       [-5.27194031e-02, -5.84433600e-02, -6.63188621e-02],
       [-3.42482072e-03,  6.33254321e-03, -1.76849688e-04],
       [ 2.67435890e-03,  8.00716877e-03,  1.34313693e-02],
       [ 5.84662035e-02,  4.80714403e-02,  2.89580855e-03],
       [-5.77450506e-02, -4.27695662e-02, -3.53884995e-02]], dtype=float32)

In [18]:
r_1

array([[ 0.00286266, -0.01719058, -0.02098264, ...,  0.02597624,
         0.03359259,  0.01350135],
       [-0.01783724,  0.01417158,  0.01664465, ..., -0.01463804,
        -0.06240278, -0.10009476],
       [-0.00037298,  0.00231852, -0.0156411 , ...,  0.0174076 ,
         0.00553678, -0.01473506],
       ...,
       [-0.01783776,  0.0252948 ,  0.00650783, ..., -0.00531552,
        -0.06705691, -0.11491743],
       [-0.00798607,  0.07357194,  0.0530423 , ..., -0.07121161,
        -0.11412936, -0.05924034],
       [-0.01416983,  0.06078571, -0.00410874, ..., -0.00160455,
        -0.08540038, -0.1259494 ]], dtype=float32)

In [6]:
input_path = Path('../results/sks/hedgehog')
dataname = input_path / "model.ply"
pcd = o3d.io.read_point_cloud(str(dataname))

In [7]:
help(pcd)

Help on PointCloud in module open3d.cpu.pybind.geometry object:

class PointCloud(Geometry3D)
 |  PointCloud class. A point cloud consists of point coordinates, and optionally point colors and point normals.
 |
 |  Method resolution order:
 |      PointCloud
 |      Geometry3D
 |      Geometry
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __add__(...)
 |      __add__(self: open3d.cpu.pybind.geometry.PointCloud, arg0: open3d.cpu.pybind.geometry.PointCloud) -> open3d.cpu.pybind.geometry.PointCloud
 |
 |  __copy__(...)
 |      __copy__(self: open3d.cpu.pybind.geometry.PointCloud) -> open3d.cpu.pybind.geometry.PointCloud
 |
 |  __deepcopy__(...)
 |      __deepcopy__(self: open3d.cpu.pybind.geometry.PointCloud, arg0: dict) -> open3d.cpu.pybind.geometry.PointCloud
 |
 |  __iadd__(...)
 |      __iadd__(self: open3d.cpu.pybind.geometry.PointCloud, arg0: open3d.cpu.pybind.geometry.PointCloud) -> open3d.cpu.pybind.geometry.PointCloud
 |
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |
 |      1. __init__(self: open3d.cpu.pybind.geometry.PointCloud) -> None
 |
 |      Default constructor
 |
 |      2. __init__(self: open3d.cpu.pybind.geometry.PointCloud, arg0: open3d.cpu.pybind.geometry.PointCloud) -> None
 |
 |      Copy constructor
 |
 |      3. __init__(self: open3d.cpu.pybind.geometry.PointCloud, points: open3d.cpu.pybind.utility.Vector3dVector) -> None
 |
 |      Create a PointCloud from points
 |
 |  __repr__(...)
 |      __repr__(self: open3d.cpu.pybind.geometry.PointCloud) -> str
 |
 |  cluster_dbscan(...)
 |      cluster_dbscan(self, eps, min_points, print_progress=False)
 |      Cluster PointCloud using the DBSCAN algorithm  Ester et al., 'A Density-Based Algorithm for Discovering Clusters in Large Spatial Databases with Noise', 1996. Returns a list of point labels, -1 indicates noise according to the algorithm.
 |
 |      Args:
 |          eps (float): Density parameter that is used to find neighbouring points.
 |          min_points (int): Minimum number of points to form a cluster.
 |          print_progress (bool, optional, default=False): If true the progress is visualized in the console.
 |
 |      Returns:
 |          open3d.utility.IntVector
 |
 |  compute_convex_hull(...)
 |      compute_convex_hull(self: open3d.cpu.pybind.geometry.PointCloud, joggle_inputs: bool = False) -> Tuple[open3d::geometry::TriangleMesh, List[int]]
 |
 |
 |      Computes the convex hull of the point cloud.
 |
 |      Args:
 |           joggle_inputs (bool): If True allows the algorithm to add random noise to
 |                the points to work around degenerate inputs. This adds the 'QJ'
 |                option to the qhull command.
 |
 |      Returns:
 |           tuple(open3d.geometry.TriangleMesh, list): The triangle mesh of the convex
 |           hull and the list of point indices that are part of the convex hull.
 |
 |  compute_mahalanobis_distance(...)
 |      compute_mahalanobis_distance(self)
 |      Function to compute the Mahalanobis distance for points in a point cloud. See: https://en.wikipedia.org/wiki/Mahalanobis_distance.
 |
 |      Returns:
 |          open3d.utility.DoubleVector
 |
 |  compute_mean_and_covariance(...)
 |      compute_mean_and_covariance(self)
 |      Function to compute the mean and covariance matrix of a point cloud.
 |
 |      Returns:
 |          Tuple[numpy.ndarray[numpy.float64[3, 1]], numpy.ndarray[numpy.float64[3, 3]]]
 |
 |  compute_nearest_neighbor_distance(...)
 |      compute_nearest_neighbor_distance(self)
 |      Function to compute the distance from a point to its nearest neighbor in the point cloud
 |
 |      Returns:
 |          open3d.utility.DoubleVector
 |
 |  compute_point_cloud_distance(...)
 |      compute_point_cloud_distance(self, target)
 |      For each point in the source point cloud, compute the distance to the target point cloud.
 |
 |      Args:
 |          target (open3d.geometry.PointCloud): The target point cloud.
 |
 |      Returns:
 |          open3d.utility.DoubleVector
 |
 |  crop(...)
 |      crop(*args, **kwargs)
 |      Overloaded function.
 |
 |
 |      1. crop(self, bounding_box, invert=False)
 |          Function to crop input pointcloud into output pointcloud
 |
 |      Args:
 |          bounding_box (open3d.geometry.AxisAlignedBoundingBox): AxisAlignedBoundingBox to crop points
 |          invert (bool, optional, default=False): optional boolean to invert cropping
 |
 |      Returns:
 |          open3d.geometry.PointCloud
 |
 |      2. crop(self, bounding_box, invert=False)
 |          Function to crop input pointcloud into output pointcloud
 |
 |      Args:
 |          bounding_box (open3d.geometry.OrientedBoundingBox): AxisAlignedBoundingBox to crop points
 |          invert (bool, optional, default=False): optional boolean to invert cropping
 |
 |      Returns:
 |          open3d.geometry.PointCloud
 |
 |  detect_planar_patches(...)
 |      detect_planar_patches(self, normal_variance_threshold_deg=60, coplanarity_deg=75, outlier_ratio=0.75, min_plane_edge_length=0.0, min_num_points=0, search_param=KDTreeSearchParamKNN with knn = 30)
 |      Detects planar patches in the point cloud using a robust statistics-based approach.
 |
 |      Returns:
 |           A list of detected planar patches, represented as
 |           OrientedBoundingBox objects, with the third column (z) of R indicating
 |           the planar patch normal vector. The extent in the z direction is
 |           non-zero so that the OrientedBoundingBox contains the points that
 |           contribute to the plane detection.
 |
 |      Args:
 |          normal_variance_threshold_deg (float, optional, default=60)
 |          coplanarity_deg (float, optional, default=75)
 |          outlier_ratio (float, optional, default=0.75): Maximum allowable ratio of outliers associated to a plane.
 |          min_plane_edge_length (float, optional, default=0.0): Minimum edge length of plane's long edge before being rejected.
 |          min_num_points (int, optional, default=0): Minimum number of points allowable for fitting planes.
 |          search_param (open3d.geometry.KDTreeSearchParam, optional, default=KDTreeSearchParamKNN with knn = 30): The KDTree search parameters for neighborhood search.
 |
 |      Returns:
 |          List[open3d.geometry.OrientedBoundingBox]
 |
 |  estimate_covariances(...)
 |      estimate_covariances(self, search_param=KDTreeSearchParamKNN with knn = 30)
 |      Function to compute the covariance matrix for each point in the point cloud
 |
 |      Args:
 |          search_param (open3d.geometry.KDTreeSearchParam, optional, default=KDTreeSearchParamKNN with knn = 30): The KDTree search parameters for neighborhood search.
 |
 |      Returns:
 |          None
 |
 |  estimate_normals(...)
 |      estimate_normals(self, search_param=KDTreeSearchParamKNN with knn = 30, fast_normal_computation=True)
 |      Function to compute the normals of a point cloud. Normals are oriented with respect to the input point cloud if normals exist
 |
 |      Args:
 |          search_param (open3d.geometry.KDTreeSearchParam, optional, default=KDTreeSearchParamKNN with knn = 30): The KDTree search parameters for neighborhood search.
 |          fast_normal_computation (bool, optional, default=True): If true, the normal estimation uses a non-iterative method to extract the eigenvector from the covariance matrix. This is faster, but is not as numerical stable.
 |
 |      Returns:
 |          None
 |
 |  farthest_point_down_sample(...)
 |      farthest_point_down_sample(self: open3d.cpu.pybind.geometry.PointCloud, num_samples: int) -> open3d.cpu.pybind.geometry.PointCloud
 |
 |      Downsamples input pointcloud into output pointcloud with a set of points has farthest distance. The sample is performed by selecting the farthest point from previous selected points iteratively.
 |
 |  has_colors(...)
 |      has_colors(self)
 |      Returns ``True`` if the point cloud contains point colors.
 |
 |      Returns:
 |          bool
 |
 |  has_covariances(...)
 |      has_covariances(self: open3d.cpu.pybind.geometry.PointCloud) -> bool
 |
 |      Returns ``True`` if the point cloud contains covariances.
 |
 |  has_normals(...)
 |      has_normals(self)
 |      Returns ``True`` if the point cloud contains point normals.
 |
 |      Returns:
 |          bool
 |
 |  has_points(...)
 |      has_points(self)
 |      Returns ``True`` if the point cloud contains points.
 |
 |      Returns:
 |          bool
 |
 |  hidden_point_removal(...)
 |      hidden_point_removal(self, camera_location, radius)
 |      Removes hidden points from a point cloud and returns a mesh of the remaining points. Based on Katz et al. 'Direct Visibility of Point Sets', 2007. Additional information about the choice of radius for noisy point clouds can be found in Mehra et. al. 'Visibility of Noisy Point Cloud Data', 2010.
 |
 |      Args:
 |          camera_location (numpy.ndarray[numpy.float64[3, 1]]): All points not visible from that location will be removed
 |          radius (float): The radius of the sperical projection
 |
 |      Returns:
 |          Tuple[open3d.geometry.TriangleMesh, List[int]]
 |
 |  normalize_normals(...)
 |      normalize_normals(self)
 |      Normalize point normals to length 1.
 |
 |      Returns:
 |          open3d.geometry.PointCloud
 |
 |  orient_normals_consistent_tangent_plane(...)
 |      orient_normals_consistent_tangent_plane(self, k, lambda=0.0, cos_alpha_tol=1.0)
 |      Function to orient the normals with respect to consistent tangent planes
 |
 |      Args:
 |          k (int): Number of k nearest neighbors used in constructing the Riemannian graph used to propagate normal orientation.
 |          lambda (float, optional, default=0.0)
 |          cos_alpha_tol (float, optional, default=1.0)
 |
 |      Returns:
 |          None
 |
 |  orient_normals_to_align_with_direction(...)
 |      orient_normals_to_align_with_direction(self, orientation_reference=array([0., 0., 1.]))
 |      Function to orient the normals of a point cloud
 |
 |      Args:
 |          orientation_reference (numpy.ndarray[numpy.float64[3, 1]], optional, default=array([0., 0., 1.])): Normals are oriented with respect to orientation_reference.
 |
 |      Returns:
 |          None
 |
 |  orient_normals_towards_camera_location(...)
 |      orient_normals_towards_camera_location(self, camera_location=array([0., 0., 0.]))
 |      Function to orient the normals of a point cloud
 |
 |      Args:
 |          camera_location (numpy.ndarray[numpy.float64[3, 1]], optional, default=array([0., 0., 0.])): Normals are oriented with towards the camera_location.
 |
 |      Returns:
 |          None
 |
 |  paint_uniform_color(...)
 |      paint_uniform_color(self, color)
 |      Assigns each point in the PointCloud the same color.
 |
 |      Args:
 |          color (numpy.ndarray[numpy.float64[3, 1]]): RGB color for the PointCloud.
 |
 |      Returns:
 |          open3d.geometry.PointCloud
 |
 |  random_down_sample(...)
 |      random_down_sample(self, sampling_ratio)
 |      Function to downsample input pointcloud into output pointcloud randomly. The sample is generated by randomly sampling the indexes from the point cloud.
 |
 |      Args:
 |          sampling_ratio (float): Sampling ratio, the ratio of number of selected points to total number of points[0-1]
 |
 |      Returns:
 |          open3d.geometry.PointCloud
 |
 |  remove_duplicated_points(...)
 |      remove_duplicated_points(self)
 |      Removes duplicated points, i.e., points that have identical coordinates. It also removes the corresponding attributes associated with the non-finite point such as normals, covariances and color entries. It doesn't re-computes these attributes after removing duplicated points.
 |
 |      Returns:
 |          open3d.geometry.PointCloud
 |
 |  remove_non_finite_points(...)
 |      remove_non_finite_points(self, remove_nan=True, remove_infinite=True)
 |      Removes all points from the point cloud that have a nan entry, or infinite entries. It also removes the corresponding attributes associated with the non-finite point such as normals, covariances and color entries. It doesn't re-computes these attributes after removing non-finite points.
 |
 |      Args:
 |          remove_nan (bool, optional, default=True): Remove NaN values from the PointCloud
 |          remove_infinite (bool, optional, default=True): Remove infinite values from the PointCloud
 |
 |      Returns:
 |          open3d.geometry.PointCloud
 |
 |  remove_radius_outlier(...)
 |      remove_radius_outlier(self, nb_points, radius, print_progress=False)
 |      Removes points that have neighbors less than nb_points in a sphere of a given radius
 |
 |      Args:
 |          nb_points (int): Number of points within the radius.
 |          radius (float): Radius of the sphere.
 |          print_progress (bool, optional, default=False): Set to True to print progress bar.
 |
 |      Returns:
 |          Tuple[open3d.geometry.PointCloud, List[int]]
 |
 |  remove_statistical_outlier(...)
 |      remove_statistical_outlier(self, nb_neighbors, std_ratio, print_progress=False)
 |      Removes points that are further away from their neighbors in average.
 |
 |      Args:
 |          nb_neighbors (int): Number of neighbors around the target point.
 |          std_ratio (float): Standard deviation ratio.
 |          print_progress (bool, optional, default=False): Set to True to print progress bar.
 |
 |      Returns:
 |          Tuple[open3d.geometry.PointCloud, List[int]]
 |
 |  segment_plane(...)
 |      segment_plane(self, distance_threshold, ransac_n, num_iterations, probability=0.99999999)
 |      Segments a plane in the point cloud using the RANSAC algorithm.
 |
 |      Args:
 |          distance_threshold (float): Max distance a point can be from the plane model, and still be considered an inlier.
 |          ransac_n (int): Number of initial points to be considered inliers in each iteration.
 |          num_iterations (int): Number of iterations.
 |          probability (float, optional, default=0.99999999): Expected probability of finding the optimal plane.
 |
 |      Returns:
 |          Tuple[numpy.ndarray[numpy.float64[4, 1]], List[int]]
 |
 |  select_by_index(...)
 |      select_by_index(self, indices, invert=False)
 |      Function to select points from input pointcloud into output pointcloud.
 |
 |      Args:
 |          indices (List[int]): Indices of points to be selected.
 |          invert (bool, optional, default=False): Set to ``True`` to invert the selection of indices.
 |
 |      Returns:
 |          open3d.geometry.PointCloud
 |
 |  uniform_down_sample(...)
 |      uniform_down_sample(self, every_k_points)
 |      Function to downsample input pointcloud into output pointcloud uniformly. The sample is performed in the order of the points with the 0-th point always chosen, not at random.
 |
 |      Args:
 |          every_k_points (int): Sample rate, the selected point indices are [0, k, 2k, ...]
 |
 |      Returns:
 |          open3d.geometry.PointCloud
 |
 |  voxel_down_sample(...)
 |      voxel_down_sample(self, voxel_size)
 |      Function to downsample input pointcloud into output pointcloud with a voxel. Normals and colors are averaged if they exist.
 |
 |      Args:
 |          voxel_size (float): Voxel size to downsample into.
 |
 |      Returns:
 |          open3d.geometry.PointCloud
 |
 |  voxel_down_sample_and_trace(...)
 |      voxel_down_sample_and_trace(self, voxel_size, min_bound, max_bound, approximate_class=False)
 |      Function to downsample using PointCloud.VoxelDownSample. Also records point cloud index before downsampling
 |
 |      Args:
 |          voxel_size (float): Voxel size to downsample into.
 |          min_bound (numpy.ndarray[numpy.float64[3, 1]]): Minimum coordinate of voxel boundaries
 |          max_bound (numpy.ndarray[numpy.float64[3, 1]]): Maximum coordinate of voxel boundaries
 |          approximate_class (bool, optional, default=False)
 |
 |      Returns:
 |          Tuple[open3d.geometry.PointCloud, numpy.ndarray[numpy.int32[m, n]], List[open3d.utility.IntVector]]
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  create_from_depth_image(...) from builtins.PyCapsule
 |      create_from_depth_image(depth, intrinsic, extrinsic=(with default value), depth_scale=1000.0, depth_trunc=1000.0, stride=1, project_valid_depth_only=True)
 |      Factory function to create a pointcloud from a depth image and a
 |      camera. Given depth value d at (u, v) image coordinate, the corresponding 3d point is:
 |
 |          - z = d / depth_scale
 |          - x = (u - cx) * z / fx
 |          - y = (v - cy) * z / fy
 |
 |      Args:
 |          depth (open3d.geometry.Image): The input depth image can be either a float image, or a uint16_t image.
 |          intrinsic (open3d.camera.PinholeCameraIntrinsic): Intrinsic parameters of the camera.
 |          extrinsic (numpy.ndarray[numpy.float64[4, 4]], optional) Default value:
 |
 |              array([[1., 0., 0., 0.],
 |              [0., 1., 0., 0.],
 |              [0., 0., 1., 0.],
 |              [0., 0., 0., 1.]])
 |          depth_scale (float, optional, default=1000.0): The depth is scaled by 1 / depth_scale.
 |          depth_trunc (float, optional, default=1000.0): Truncated at depth_trunc distance.
 |          stride (int, optional, default=1): Sampling factor to support coarse point cloud extraction.
 |          project_valid_depth_only (bool, optional, default=True)
 |
 |      Returns:
 |          open3d.geometry.PointCloud
 |
 |  create_from_rgbd_image(...) from builtins.PyCapsule
 |      create_from_rgbd_image(image, intrinsic, extrinsic=(with default value), project_valid_depth_only=True)
 |      Factory function to create a pointcloud from an RGB-D image and a camera. Given depth value d at (u, v) image coordinate, the corresponding 3d point is:
 |
 |          - z = d / depth_scale
 |          - x = (u - cx) * z / fx
 |          - y = (v - cy) * z / fy
 |
 |      Args:
 |          image (open3d.geometry.RGBDImage): The input image.
 |          intrinsic (open3d.camera.PinholeCameraIntrinsic): Intrinsic parameters of the camera.
 |          extrinsic (numpy.ndarray[numpy.float64[4, 4]], optional) Default value:
 |
 |              array([[1., 0., 0., 0.],
 |              [0., 1., 0., 0.],
 |              [0., 0., 1., 0.],
 |              [0., 0., 0., 1.]])
 |          project_valid_depth_only (bool, optional, default=True)
 |
 |      Returns:
 |          open3d.geometry.PointCloud
 |
 |  estimate_point_covariances(...) from builtins.PyCapsule
 |      estimate_point_covariances(input, search_param=KDTreeSearchParamKNN with knn = 30)
 |      Static function to compute the covariance matrix for each point in the given point cloud, doesn't change the input
 |
 |      Args:
 |          input (open3d.geometry.PointCloud): The input point cloud.
 |          search_param (open3d.geometry.KDTreeSearchParam, optional, default=KDTreeSearchParamKNN with knn = 30): The KDTree search parameters for neighborhood search.
 |
 |      Returns:
 |          open3d.utility.Matrix3dVector
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  colors
 |      ``float64`` array of shape ``(num_points, 3)``, range ``[0, 1]`` , use ``numpy.asarray()`` to access data: RGB colors of points.
 |
 |  covariances
 |      ``float64`` array of shape ``(num_points, 3, 3)``, use ``numpy.asarray()`` to access data: Points covariances.
 |
 |  normals
 |      ``float64`` array of shape ``(num_points, 3)``, use ``numpy.asarray()`` to access data: Points normals.
 |
 |  points
 |      ``float64`` array of shape ``(num_points, 3)``, use ``numpy.asarray()`` to access data: Points coordinates.
 |

In [8]:
o3d.visualization.draw_geometries([pcd])

In [9]:
points = np.asarray(pcd.points)

In [10]:
means, covs = pcd.compute_mean_and_covariance()

In [11]:
means

array([0.08622234, 0.0396085 , 0.03513216])

In [12]:
x = (points[:, 0] - means[0]) / np.sqrt(covs[0, 0])
y = (points[:, 1] - means[1]) / np.sqrt(covs[1, 1])
z = (points[:, 2] - means[2]) / np.sqrt(covs[2, 2])

In [13]:
x

array([ 0.43080752,  0.73583915,  1.02379256, ..., -0.85653032,
       -1.13465734,  0.24886366])

In [14]:
np.asarray(pcd.points)

array([[ 0.48159379,  0.85069793, -0.19631873],
       [ 0.76153505,  0.71680242, -0.21477644],
       [ 1.02580285,  0.26997077, -0.12012614],
       ...,
       [-0.69985408, -0.01613231, -0.20856708],
       [-0.95510375,  0.7920242 , -0.20227396],
       [ 0.31461573, -0.63802236,  0.13772844]])

Initialized covariances for Gaussian Splats (in paper they take $3$ nearest neighbours)

In [17]:
downpcd = pcd.voxel_down_sample(voxel_size=0.02)

In [18]:
np.asarray(downpcd.points)

array([[-0.89409775,  0.59787546,  0.03564217],
       [-0.94275117,  1.65195334,  0.04753051],
       [-0.10541813, -0.32158026, -0.00740856],
       ...,
       [-1.30845523, -0.09112357, -0.21711229],
       [ 0.85056585,  0.43182588,  0.18834117],
       [ 0.31461573, -0.63802236,  0.13772844]])

In [19]:
o3d.visualization.draw_geometries([downpcd])

In [23]:
downpcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
downpcd.normalize_normals()

PointCloud with 125320 points.

In [22]:
o3d.visualization.draw_geometries([downpcd], point_show_normal=True)

In [26]:
model_pc = PyntCloud.from_file(str(dataname))

In [27]:
model_pc.points['normals'] =

,x,y,z,a,q0,q1,q2,q3,s0,s1,...,sh12_z,sh13_x,sh13_y,sh13_z,sh14_x,sh14_y,sh14_z,sh15_x,sh15_y,sh15_z
0,0.481594,0.850698,-0.196319,-1.289389,1.053202,0.777928,0.666606,0.782969,-6.069666,-8.106468,...,0.098698,0.003610,0.001742,-0.002101,0.030575,0.025658,0.040775,-0.126277,-0.111762,-0.132224
1,0.761535,0.716802,-0.214776,-1.244070,0.821183,0.930334,-0.177495,0.306206,-3.758905,-5.277179,...,0.022767,-0.047945,-0.037082,-0.095535,0.016211,0.015260,0.024990,0.004395,0.041731,0.004630
2,1.025803,0.269971,-0.120126,-1.104922,0.551044,-0.194463,1.281180,0.393679,-8.181364,-7.613200,...,0.054696,0.032633,0.008218,-0.129743,0.057082,0.067569,0.058694,0.037657,0.036729,0.033269
3,0.475272,0.124009,-0.075317,1.125659,0.566566,0.463456,0.774790,0.489841,-3.742359,-4.793444,...,-0.058047,-0.000428,0.003574,-0.023057,-0.012539,-0.001188,0.000045,-0.044469,-0.053430,-0.051161
4,0.798120,1.040688,-0.023332,1.319954,-0.165604,0.268248,1.040911,0.002683,-6.472095,-7.021164,...,0.025024,-0.016341,-0.024041,-0.023883,0.051209,0.042731,0.051137,0.003423,-0.010310,-0.014037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3685994,-0.212520,0.033916,-0.080550,-0.867877,0.641948,0.461006,0.553307,1.264350,-4.994217,-18.804882,...,-0.022673,-0.033227,-0.100685,-0.082938,-0.024404,0.012880,0.025330,-0.239103,-0.078461,-0.113968
3685995,0.850566,0.431826,0.188341,-2.093014,0.971840,0.620849,0.431704,1.022836,-3.138559,-3.887674,...,0.028839,-0.060037,-0.064375,-0.073136,0.006281,0.005287,-0.003834,0.148534,0.152696,0.154640
3685996,-0.699854,-0.016132,-0.208567,0.350056,0.083633,1.758122,-0.455008,-0.033128,-4.300349,-7.180073,...,0.034278,0.086976,0.076210,0.038362,0.024849,0.032772,-0.003208,-0.104244,-0.098325,-0.103457
3685997,-0.955104,0.792024,-0.202274,-2.293873,1.259638,0.916563,0.488875,0.613027,-4.011404,-8.201948,...,0.019209,0.010984,0.007131,0.017476,0.011271,0.008107,0.033964,0.022125,0.066955,0.087904
3685998,0.314616,-0.638022,0.137728,-2.929590,0.558969,0.332812,-0.025434,0.901521,-2.780837,-20.197399,...,-0.007888,-0.008093,-0.005922,0.042721,0.084852,0.093813,0.049113,-0.141319,-0.174680,-0.149751

In [33]:
pcd.estimate_covariances(search_param=o3d.geometry.KDTreeSearchParamKNN(knn=3))

In [34]:
np.asarray(pcd.covariances).shape

(57713, 3, 3)

In [35]:
np.asarray(pcd.covariances)

array([[[ 4.40035488e-06,  5.18352433e-06, -2.34802091e-06],
        [ 5.18352433e-06,  2.37572806e-05, -9.66981102e-07],
        [-2.34802091e-06, -9.66981102e-07,  1.43623974e-06]],

       [[ 4.73576503e-06, -4.82237335e-06, -2.52145564e-06],
        [-4.82237335e-06,  1.59538810e-04,  3.89899952e-05],
        [-2.52145564e-06,  3.89899952e-05,  9.92173683e-06]],

       [[ 1.40935021e-05, -1.58921606e-05, -3.16675383e-06],
        [-1.58921606e-05,  1.79745733e-05,  3.47416011e-06],
        [-3.16675383e-06,  3.47416011e-06,  8.84232110e-07]],

       ...,

       [[ 8.31561856e-07,  4.98318861e-06,  2.40292229e-06],
        [ 4.98318861e-06,  3.03139807e-05,  1.65226192e-05],
        [ 2.40292229e-06,  1.65226192e-05,  1.69169102e-05]],

       [[ 8.16336073e-06,  3.23510115e-06,  6.28683944e-06],
        [ 3.23510115e-06,  2.88765916e-06,  3.42536967e-06],
        [ 6.28683944e-06,  3.42536967e-06,  5.38490860e-06]],

       [[ 7.93813724e-07, -2.92393777e-06,  3.74944517e-06],
        [-2.92393777e-06,  1.09527637e-05, -1.57556620e-05],
        [ 3.74944517e-06, -1.57556620e-05,  3.84129509e-05]]])

In [36]:
np.save(input_path / 'undistorted_images/cov_3d.npy', np.asarray(pcd.covariances))

In [7]:
o3d.visualization.draw_geometries([pcd])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid.

In [11]:
np.asarray(pcd.colors)

array([[0.7372549 , 0.63529412, 0.58431373],
       [0.22745098, 0.21176471, 0.17254902],
       [0.73333333, 0.74117647, 0.72941176],
       ...,
       [0.58039216, 0.48235294, 0.45098039],
       [0.35686275, 0.34117647, 0.31764706],
       [0.04313725, 0.07843137, 0.06666667]])